#
# Copyright (c) 2023-2026 Mariano Barcia
#
# Licensed under the Apache License, Version 2.0 (the "License");
#

quarkus.log.category."org.pipelineframework".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] (%t) %s%e%n
quarkus.otel.metric.export.interval=10
quarkus.log.category."io.quarkus.opentelemetry.runtime.QuarkusContextStorage".level=WARN
