#
# Copyright (c) 2023-2026 Mariano Barcia
#
# Licensed under the Apache License, Version 2.0 (the "License");
#

quarkus.http.test-port=0

quarkus.otel.enabled=false
quarkus.otel.traces.enabled=false
quarkus.otel.metrics.enabled=false
quarkus.otel.logs.enabled=false
quarkus.otel.sdk.disabled=true
quarkus.observability.lgtm.enabled=false

quarkus.micrometer.export.prometheus.enabled=false
