quarkus.http.port=${PIPELINE_RUNTIME_GRPC_PORT:9000}
quarkus.grpc.server.use-separate-server=false
pipeline.health.enabled=false

pipeline.module.pipeline-runtime-svc.steps=process-checkout-validate-request,\
  process-checkout-create-pending,\
  process-consumer-validate-order,\
  process-restaurant-accept-order,\
  process-kitchen-expand-tasks,\
  process-kitchen-reduce-completion,\
  process-dispatch-assign-courier,\
  process-delivery-execute-order,\
  process-payment-capture-order,\
  process-compensation-finalize-order
