version: 2
appName: Checkout Create Order Pipeline
basePackage: org.pipelineframework.checkout.createorder
transport: GRPC
types:
  OrderRequest:
    fields:
      - [requestId, uuid]
      - [customerId, uuid]
      - name: items
        type: OrderLineItem
        repeated: true
  OrderLineItem:
    fields:
      - [requestId, uuid]
      - [customerId, uuid]
      - [sku, string]
      - [quantity, int32]
  InitialOrder:
    fields:
      - [orderId, uuid]
      - [requestId, uuid]
      - [customerId, uuid]
      - [itemCount, int32]
  ReadyOrder:
    fields:
      - [orderId, uuid]
      - [requestId, uuid]
      - [customerId, uuid]
      - [readyAt, timestamp]
contract:
  input: OrderRequest
  output: ReadyOrder
steps:
  - name: Order Request Process
    cardinality: ONE_TO_MANY
    output: OrderLineItem
  - name: Order Create
    cardinality: MANY_TO_ONE
    output: InitialOrder
  - name: Order Ready
    cardinality: ONE_TO_ONE
    output: ReadyOrder
