pipeline.orchestrator.mode=QUEUE_ASYNC
pipeline.orchestrator.idempotency-policy=CLIENT_KEY_REQUIRED
pipeline.module.pipeline-runtime-svc.host=${PIPELINE_RUNTIME_HOST:127.0.0.1}
pipeline.module.pipeline-runtime-svc.port=${PIPELINE_RUNTIME_GRPC_PORT:9000}
